// Objective-C API for talking to github.com/naoty/gobind_playground/greeting Go package.
//   gobind -lang=objc github.com/naoty/gobind_playground/greeting
//
// File is generated by gobind. Do not edit.

#ifndef __GoGreeting_H__
#define __GoGreeting_H__

#include <Foundation/Foundation.h>


@class GoGreetingPerson;

@protocol GoGreetingGreetable
- (void)Greet:(NSString*)word;
@end

@interface GoGreetingPerson : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)Name;
- (void)setName:(NSString*)v;
- (int)Age;
- (void)setAge:(int)v;
- (BOOL)Married;
- (void)setMarried:(BOOL)v;
@end

FOUNDATION_EXPORT void GoGreetingHello();

FOUNDATION_EXPORT NSString* GoGreetingNewGreeting(NSString* word, NSString* name);

#endif
